# Generated by Django 5.2.7 on 2025-12-18 23:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('age', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Yaş')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1, verbose_name='Cinsiyet')),
                ('nationality', models.CharField(default='Unknown', max_length=50, verbose_name='Milliyet')),
                ('flight_id', models.CharField(max_length=10, verbose_name='Uçuş Numarası (Flight ID)')),
                ('seat_type', models.CharField(choices=[('business', 'Business'), ('economy', 'Economy')], default='economy', max_length=10, verbose_name='Koltuk Tipi')),
                ('seat_number', models.CharField(blank=True, max_length=5, null=True, verbose_name='Koltuk No')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infants', to='passengers.passenger', verbose_name='Ebeveyn (Bebekler için)')),
            ],
        ),
    ]
