# Generated by Django 5.2.7 on 2025-12-10 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(default=25, verbose_name='Yaş'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='flight_id',
            field=models.CharField(default='TR0000', max_length=10, verbose_name='Uçuş Numarası (Flight ID)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1, verbose_name='Cinsiyet'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Milliyet'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infants', to='passengers.passenger', verbose_name='Ebeveyn (Bebekler için)'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Koltuk No'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_type',
            field=models.CharField(choices=[('business', 'Business'), ('economy', 'Economy')], default='economy', max_length=10, verbose_name='Koltuk Tipi'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Soyad'),
        ),
    ]
