# Generated by Django 5.2.7 on 2025-12-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('seniority_level', models.CharField(choices=[('senior', 'Senior Pilot'), ('junior', 'Junior Pilot'), ('trainee', 'Trainee')], default='trainee', max_length=20)),
                ('allowed_range', models.IntegerField()),
                ('vehicle_restriction', models.CharField(max_length=50)),
                ('languages', models.ManyToManyField(blank=True, to='flight_crew_service.language')),
            ],
        ),
    ]
