# Generated by Django 5.2.7 on 2025-12-18 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabincrew_api', '0001_initial'),
        ('flight_crew_service', '0001_initial'),
        ('flights', '0001_initial'),
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.JSONField(blank=True, null=True, verbose_name='Uçuş Menüsü')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='Roster Onaylandı mı?')),
                ('is_generated', models.BooleanField(default=False, help_text='Otomatik oluşturma tamamlandı mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cabin_crew', models.ManyToManyField(related_name='rosters', to='cabincrew_api.cabincrew')),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='flights.flight')),
                ('passengers', models.ManyToManyField(blank=True, related_name='rosters', to='passengers.passenger')),
                ('pilots', models.ManyToManyField(related_name='rosters', to='flight_crew_service.pilot')),
            ],
        ),
    ]
