# Generated by Django 5.2.7 on 2025-12-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightroster',
            name='menu',
            field=models.JSONField(blank=True, null=True, verbose_name='Uçuş Menüsü'),
        ),
    ]
