# Generated by Django 5.2.7 on 2025-12-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0002_flightroster_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightroster',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='Roster Onaylandı mı?'),
        ),
    ]
