# Generated by Django 5.2.7 on 2025-12-11 20:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Airport code must be 3 uppercase letters.', regex='^[A-Z]{3}$')])),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('seat_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('seating_plan', models.JSONField(blank=True, null=True)),
                ('max_crew', models.PositiveIntegerField(default=6)),
                ('max_passengers', models.PositiveIntegerField()),
                ('standard_menu', models.JSONField(blank=True, help_text='Standard menu served on this plane', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Flight number must be in AANNNN format (e.g. HVB1234).', regex='^HB\\d{4}$')])),
                ('departure_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('distance_km', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='flights.airport')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='flights.airport')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='SharedFlightInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_airline', models.CharField(max_length=100)),
                ('partner_flight_number', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Flight number must be in AANNNN format (e.g. HVB1234).', regex='^HB\\d{4}$')])),
                ('connecting_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_to', to='flights.flight')),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_info', to='flights.flight')),
            ],
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_datetime'], name='flights_fli_departu_f18c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['flight_number'], name='flights_fli_flight__794da4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('flight_number',)},
        ),
    ]
