# Generated by Django 5.2.7 on 2025-12-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabincrew_api', '0002_rename_senority_level_cabincrew_seniority_level'),
        ('flight_crew_service', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='cabin_crew',
            field=models.ManyToManyField(blank=True, related_name='flights', to='cabincrew_api.cabincrew', verbose_name='cabin crew'),
        ),
        migrations.AddField(
            model_name='flight',
            name='pilots',
            field=models.ManyToManyField(blank=True, related_name='flights', to='flight_crew_service.pilot', verbose_name='Pilots'),
        ),
    ]
