# Generated by Django 5.2.7 on 2025-11-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='seating_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
