# Generated by Django 5.2.7 on 2025-11-30 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_vehicletype_seating_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedflightinfo',
            name='partner_airline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('flight_number',)},
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Flight number must be in AANNNN format (e.g. HVB1234).', regex='^HVB\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='sharedflightinfo',
            name='partner_flight_number',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Flight number must be in AANNNN format (e.g. HVB1234).', regex='^HVB\\d{3}$')]),
        ),
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.DeleteModel(
            name='Airline',
        ),
    ]
