# Generated by Django 5.2.7 on 2025-12-18 23:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabinCrew',
            fields=[
                ('attendant_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('attendant_type', models.CharField(choices=[('chief', 'Chief'), ('regular', 'Regular'), ('chef', 'Chef')], max_length=10)),
                ('seniority_level', models.CharField(choices=[('senior', 'Senior Attendant'), ('junior', 'Junior Attendant'), ('chef', 'Chef Role')], max_length=10)),
            ],
            options={
                'verbose_name': 'Cabin Crew Attendant ',
                'verbose_name_plural': 'Cabin Crew Attendants',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_veh', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
            },
        ),
        migrations.CreateModel(
            name='ChefRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='cabincrew_api.cabincrew')),
            ],
            options={
                'verbose_name': 'Chef Recipe',
                'verbose_name_plural': 'Chef Recipes',
            },
        ),
        migrations.AddField(
            model_name='cabincrew',
            name='known_languages',
            field=models.ManyToManyField(related_name='crew_members', to='cabincrew_api.language'),
        ),
        migrations.AddField(
            model_name='cabincrew',
            name='vehicle_restrictions',
            field=models.ManyToManyField(related_name='allowed_crew', to='cabincrew_api.vehicletype'),
        ),
    ]
