# Generated by Django 5.2.7 on 2025-12-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabincrew_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='type_veh',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
