# Generated by Django 5.2.7 on 2025-12-12 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabincrew_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabincrew',
            old_name='senority_level',
            new_name='seniority_level',
        ),
    ]
