# Generated by Django 5.2.7 on 2025-12-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabincrew_api', '0002_rename_senority_level_cabincrew_seniority_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabincrew',
            old_name='seniority_level',
            new_name='senority_level',
        ),
    ]
